name: My Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Use OPENAI API key
      env:
        API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Use the API key here in your commands or scripts
        echo "API key is: $API_KEY"
